spring:
  datasource:
    url:
    username: root
    password: root
    druid:
      initial-size: 5 #????????
      min-idle: 10 #???????
      max-active: 20 #?????
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #?????????
      stat-view-servlet: #???????????????
        login-username: druid
        login-password: druid
  redis:
    host: 192.168.10.100
    username: root
    password: root
    connect-timeout: 1s #??????
    lettuce:
      pool:
        max-active: 16 #??????
        max-idle: 8 #??????
        min-idle: 1 #??????
        time-between-eviction-runs: 10s

